// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OMYaiRegistry$Type } from "./OMYaiRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OMYaiRegistry"]: OMYaiRegistry$Type;
    ["contracts/OMYaiRegistry.sol:OMYaiRegistry"]: OMYaiRegistry$Type;
  }
}
